apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ut6k281jy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ut6k281jy-go 
  name: ut6k281jy-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ut6k281jy-go 
